
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.unitec.compiladores;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PuntoPunto = 52;
  public static final int OperadorDiferente = 12;
  public static final int Begin = 29;
  public static final int PuntoComa = 54;
  public static final int Coma = 41;
  public static final int BracketCerrar = 38;
  public static final int Until = 36;
  public static final int OperadorMayor = 13;
  public static final int OperadorDivisionSpecial = 25;
  public static final int End = 30;
  public static final int Repeat = 35;
  public static final int If = 26;
  public static final int LlaveCerrar = 46;
  public static final int DosPuntosIgual = 43;
  public static final int Of = 5;
  public static final int Var = 6;
  public static final int ParentesisCerrar = 48;
  public static final int Else = 28;
  public static final int Read = 3;
  public static final int Then = 27;
  public static final int Punto = 53;
  public static final int OperadorOr = 18;
  public static final int While = 34;
  public static final int To = 32;
  public static final int ComillaSimple = 39;
  public static final int TipoInteger = 9;
  public static final int For = 31;
  public static final int EOF = 0;
  public static final int DosPuntos = 42;
  public static final int OperadorAnd = 17;
  public static final int OperadorNot = 19;
  public static final int Function = 51;
  public static final int error = 1;
  public static final int LiteralCaracter = 56;
  public static final int ParentesisAbrir = 47;
  public static final int OperadorResta = 21;
  public static final int LlaveAbrir = 45;
  public static final int Do = 33;
  public static final int LiteralString = 58;
  public static final int ComillaDentro = 40;
  public static final int OperadorIgual = 11;
  public static final int OperadorMod = 23;
  public static final int TipoBoolean = 7;
  public static final int Identificador = 44;
  public static final int OperadorMenorIgual = 16;
  public static final int Array = 4;
  public static final int TipoChar = 8;
  public static final int OperadorSuma = 20;
  public static final int Write = 2;
  public static final int OperadorMultiplicacion = 22;
  public static final int Program = 49;
  public static final int BracketAbrir = 37;
  public static final int LiteralEntero = 55;
  public static final int OperadorDivision = 24;
  public static final int TipoString = 10;
  public static final int OperadorMayorIgual = 15;
  public static final int Procedure = 50;
  public static final int OperadorMenor = 14;
  public static final int LiteralBoolean = 57;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Write",
  "Read",
  "Array",
  "Of",
  "Var",
  "TipoBoolean",
  "TipoChar",
  "TipoInteger",
  "TipoString",
  "OperadorIgual",
  "OperadorDiferente",
  "OperadorMayor",
  "OperadorMenor",
  "OperadorMayorIgual",
  "OperadorMenorIgual",
  "OperadorAnd",
  "OperadorOr",
  "OperadorNot",
  "OperadorSuma",
  "OperadorResta",
  "OperadorMultiplicacion",
  "OperadorMod",
  "OperadorDivision",
  "OperadorDivisionSpecial",
  "If",
  "Then",
  "Else",
  "Begin",
  "End",
  "For",
  "To",
  "Do",
  "While",
  "Repeat",
  "Until",
  "BracketAbrir",
  "BracketCerrar",
  "ComillaSimple",
  "ComillaDentro",
  "Coma",
  "DosPuntos",
  "DosPuntosIgual",
  "Identificador",
  "LlaveAbrir",
  "LlaveCerrar",
  "ParentesisAbrir",
  "ParentesisCerrar",
  "Program",
  "Procedure",
  "Function",
  "PuntoPunto",
  "Punto",
  "PuntoComa",
  "LiteralEntero",
  "LiteralCaracter",
  "LiteralBoolean",
  "LiteralString"
  };
}

