import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import java.io.File;
import java.io.StringWriter;
import org.w3c.dom.CDATASection;
import org.w3c.dom.Document;
import org.w3c.dom.Element;  
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;


parser code {:
        
        @Override
	public void report_error(String message, Object info) {
            System.err.print("Syntax error: " ); 
            expected();
            System.err.println("pero se encontró el token \'" + ((Symbol)info).value + "\' en la Linea: " + ((Symbol)info).left + ", Columna: " + ((Symbol)info).right + ". " ); 
        }

        @Override
	public void syntax_error(Symbol s){
            System.err.print("Error Sintáctico: " ); 
            expected();
            System.err.println("pero se encontró el token \'" + sym.terminalNames[s.sym] + "\' en la Linea: " + s.left + ", Columna: " + s.right + ". " ); 
	}

        public void expected(){
            List<Integer> token_list = this.expected_token_ids();
            if (token_list.size() <= 0){
                    token_list = this.expected_token_ids();
            }
            String expected_tokens = "";
            for (int i = 0 ; i < token_list.size(); i++){
                    int id = token_list.get(i);
                    if (id == 1){ //error
                        continue;
                    }
                    String terminal_name = sym.terminalNames[id];
                    if (i == token_list.size() - 1){
                        expected_tokens += terminal_name;
                    }else{
                        expected_tokens += terminal_name + " , ";
                    }
            }
            System.err.print("Se esperaba alguno de los siguientes tokens: [" + expected_tokens + "] ");
        };

        public void report_fatal_error(String message, Object info) {
            throw new Error("Error Fatal Sintáctico, no se pudo recuperar del problema.");
        }

        public void unrecovered_syntax_error(Symbol s) {
        }

        @Override
        public int error_sync_size(){
            return 1;
        }
        
:};

action code {:
        /* Contruccion del arbol en XML */

        Document xmlDocument = null;    
        Element nodoPadre = null; 

        private void iniXML() {
        if (xmlDocument == null) {
            try {
                DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
                DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
                xmlDocument = docBuilder.newDocument();//Crear el documento XML
            } catch (Exception e) {
                System.err.println("el Arbol tiene ERROR: " + e.getMessage());
            }
        }
    }

    public void escribirXML() throws javax.xml.transform.TransformerConfigurationException, javax.xml.transform.TransformerException {
        //Escribir el archivo XML         
        xmlDocument.appendChild(nodoPadre);
        TransformerFactory transformerFactory = TransformerFactory.newInstance();
        Transformer transformer = transformerFactory.newTransformer();
        DOMSource origen = new DOMSource(xmlDocument);
        StreamResult result = new StreamResult(new File("AST.xml"));
        transformer.transform(origen, result);
    }
:}


/* Terminals (tokens returned by the scanner). */
//Functiones
terminal Element  Write;
terminal Element  Read;

//Tipos de datos
terminal Element  Array;
terminal Element  Of;
terminal Element  Var;
terminal String   TipoBoolean;
terminal String   TipoChar;
terminal String   TipoInteger;
terminal String   TipoString;

//Operadores
terminal String   OperadorIgual;
terminal String   OperadorDiferente;
terminal String   OperadorMayor;
terminal String   OperadorMenor;
terminal String   OperadorMayorIgual;
terminal String   OperadorMenorIgual;
terminal String   OperadorAnd;
terminal String   OperadorOr;
terminal String   OperadorNot;
terminal String   OperadorSuma;
terminal String   OperadorResta;
terminal String   OperadorMultiplicacion;
terminal String   OperadorMod;
terminal String   OperadorDivision;
terminal String   OperadorDivisionSpecial;

//Estructuras de control
terminal Element  If;
terminal Element  Then;
terminal Element  Else;
terminal Element  Begin;
terminal Element  End;
terminal Element  For;
terminal Element  To;
terminal Element  Do;
terminal Element  While;
terminal Element  Repeat;
terminal Element  Until;

//Otros
terminal String   BracketAbrir;
terminal String   BracketCerrar;
terminal String   Coma;
terminal String   DosPuntos;
terminal String   DosPuntosIgual;
terminal String   Identificador;
terminal String   LlaveAbrir;
terminal String   LlaveCerrar;
terminal String   ParentesisAbrir;
terminal String   ParentesisCerrar;
terminal String   Program;
terminal String   Procedure;
terminal String   Function;
terminal String   PuntoPunto;
terminal String   Punto;
terminal String   PuntoComa;

/*Literales*/
terminal String         LiteralEntero;
terminal Character      LiteralCaracter;
terminal String         LiteralBoolean;
terminal String         LiteralString;

/* Non terminals */
nonterminal Element              expr;
nonterminal Element              literal;
nonterminal Element              program;
nonterminal Element              block;
nonterminal Element              blockProc;
nonterminal Element              decls;
nonterminal Element              decl;
nonterminal Element              vardecls;
nonterminal Element              vardecl;
nonterminal Element              forstmt;

nonterminal Element              functionDecl;
nonterminal Element              inlineArgs;
nonterminal Element              inlineArg;
nonterminal Element              procedureDecl;
nonterminal Element              procInlineDecls;
nonterminal Element              procInlineDecl;

nonterminal Element              type;
nonterminal String               identtype;
nonterminal Element              arraytype;
nonterminal String               arrayidenttype;
nonterminal Element              vars;
nonterminal Element              var;

nonterminal Element              exprlist;
nonterminal Element              exprLogical;
nonterminal Element              exprOpLog;
nonterminal Element              opRelacion;
nonterminal Element              opArit;
nonterminal Element              opUnario;
nonterminal Element              opLogico;
nonterminal Element              stmts;
nonterminal Element              stmt;
nonterminal Element              assignstmt;
nonterminal Element              ifstmt;
nonterminal Element              whilestmt;
nonterminal Element              repeatstmt;
nonterminal Element              blockstmt;
nonterminal Element              writestmt;
nonterminal Element              readstmt;

nonterminal Element              integer;
nonterminal Element              character;
nonterminal Element              boolean;
nonterminal Element              string;


/*-* Operator Precedences **/
precedence right DosPuntosIgual;
precedence left OperadorIgual, OperadorMenor, OperadorMayor, OperadorMenorIgual, OperadorMayorIgual, OperadorDiferente;
precedence left OperadorSuma, OperadorResta, OperadorOr;
precedence left OperadorMultiplicacion, OperadorDivision, OperadorMod, OperadorDivisionSpecial, OperadorAnd;
precedence left Else, PuntoComa;
precedence left error;


program         ::= Program var:v PuntoComa block:b Punto
                {:
                    iniXML();
                    nodoPadre = xmlDocument.createElement("Program"); 
                    if (v != null) { nodoPadre.appendChild(v); }
                    if(b != null) { nodoPadre.appendChild(b); }
                    escribirXML();
                :}
                |   Program var:v1 ParentesisAbrir vars:vs ParentesisCerrar PuntoComa block:b Punto
                {:
                    iniXML();
                    nodoPadre = xmlDocument.createElement("Program"); 
                    if (v1 != null) { nodoPadre.appendChild(v1); }
                    if (vs != null) { 
                        Element nPadre = xmlDocument.createElement("ProgramArgs");
                        ArrayList<Element> asd = new ArrayList();
                        NodeList temp = vs.getChildNodes();
                        if (temp.getLength() > 0) {
                            Node parent = temp.item((temp.getLength() - 1)).getParentNode();
                            asd.add((Element) parent);
                        }
                        for (int i = 0; i < temp.getLength(); i++) {
                            asd.add((Element) temp.item(i));
                        }
                        for (int i = 0; i < asd.size(); i++) {
                            nPadre.appendChild(asd.get(i));
                        }
                        nodoPadre.appendChild(nPadre);
                    }
                    if(b != null) { nodoPadre.appendChild(b); }
                    escribirXML();
                :}
                | error block Punto
                | Program var:v PuntoComa block:b error
                ;

block           ::= decls:d Begin stmts:s End
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Block");
                    if (d != null) { nPadre.appendChild(d); }
                    if (s != null) { nPadre.appendChild(s); }
                    RESULT = nPadre;                    
                :}
                |   error End
                ;

blockProc       ::= procInlineDecls:p Begin stmts:s End
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Block");
                    if (p != null) { nPadre.appendChild(p); }
                    if (s != null) { nPadre.appendChild(s); }
                    RESULT = nPadre;                    
                :}
                |   blockProc error 
                ;

decls           ::= /* empty */ {: RESULT = null; :}
                |   decl:d decls:ds
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Declarations");
                    if (d != null && ds == null) {
                        RESULT = d;
                    } else if (d == null && ds != null){
                        RESULT = ds;
                    } else if (d != null && ds != null) {
                        nPadre.appendChild(d);
                        nPadre.appendChild(ds);
                        RESULT = nPadre;
                    } else RESULT = null;      
                :}
                |   decls:ds error 
                ;

decl            ::= Var vardecls:vd
                {:
                    iniXML();
                    RESULT = vd;
                :}
                |   functionDecl:f
                {:
                    iniXML();
                    RESULT = f;
                                        
                :}
                |   procedureDecl:p
                {:
                    iniXML();
                    RESULT = p;                   
                :}
                |   decl:d error
                ;

functionDecl    ::= Function var:i ParentesisAbrir inlineArgs:in ParentesisCerrar DosPuntos type:t PuntoComa blockProc:b PuntoComa
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("FunctionDeclaration");
                    if (i != null) { nPadre.appendChild(i); }
                    if (in != null) { nPadre.appendChild(in); }
                    if (t != null) { nPadre.appendChild(t); }
                    if (b != null) { nPadre.appendChild(b); }

                    RESULT = nPadre;                    
                :}
                |   Function var:i ParentesisAbrir ParentesisCerrar DosPuntos type:t PuntoComa blockProc:b PuntoComa
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("FunctionDeclaration");
                    if (i != null) { nPadre.appendChild(i); }
                    if (t != null) { nPadre.appendChild(t); }
                    if (b != null) { nPadre.appendChild(b); }

                    RESULT = nPadre;                    
                :}
                |   Function error
                ;

procedureDecl   ::= Procedure var:i ParentesisAbrir inlineArgs:in ParentesisCerrar PuntoComa blockProc:b PuntoComa
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ProcedureDeclaration");
                    if (i != null) { nPadre.appendChild(i); }
                    if (in != null) { nPadre.appendChild(in); }
                    if (b != null) { nPadre.appendChild(b); }

                    RESULT = nPadre;                    
                :}
                |   Procedure var:i ParentesisAbrir ParentesisCerrar PuntoComa blockProc:b PuntoComa
                {:
                    iniXML(); 
                    Element nPadre = xmlDocument.createElement("ProcedureDeclaration");
                    if (i != null) { nPadre.appendChild(i); }
                    if (b != null) { nPadre.appendChild(b); }

                    RESULT = nPadre;                    
                :}
                |   Procedure error 
                ;

procInlineDecls  ::= {: RESULT = null; :}
                |   procInlineDecl:pd procInlineDecls:pds
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ProcInlinceDecls");
                    if (pd != null && pds == null) {
                        RESULT = pd;
                    } else if(pd == null && pds != null) {
                        RESULT = pds;
                    } else if(pd != null && pds != null) {
                        nPadre.appendChild(pd);
                        nPadre.appendChild(pds);
                        RESULT = nPadre;
                    } else RESULT = null;               
                :}
                ;

procInlineDecl  ::= Var vardecls:vd
                {:
                    iniXML();
                    RESULT = vd;
                :}
                ;


inlineArgs      ::= inlineArg:ia
                {:
                    iniXML();
                    RESULT = ia;
                :}
                |   inlineArg:ia PuntoComa inlineArgs:ias
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Arguments");
                    nPadre.appendChild(ia);
                    nPadre.appendChild(ias);
                    RESULT = nPadre;
                :}
                ;

inlineArg       ::= Var vars:vs DosPuntos identtype:t
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("inlineArg");
                    if(vs != null) {
                        ArrayList<Element> asd = new ArrayList();
                        if (!vs.hasChildNodes()) {
                            nPadre.appendChild(vs);
                        } else {
                            NodeList temp = vs.getChildNodes();
                            if (temp.getLength() > 0) {
                                Node parent = temp.item((temp.getLength() - 1)).getParentNode();
                                asd.add((Element) parent);
                            }
                            for (int i = 0; i < temp.getLength(); i++) {
                                asd.add((Element) temp.item(i));
                            }
                            for (int i = 0; i < asd.size(); i++) {
                                nPadre.appendChild(asd.get(i));
                            }
                        }
                    }
                    if( t != null ) {
                        Element nType = xmlDocument.createElement("Type");
                        nType.setAttribute("Value",t);
                        nPadre.appendChild(nType);                        
                    }
                    RESULT = nPadre;
                :}
                |   vars:vs DosPuntos identtype:t 
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("inlineArg");
                    if(vs != null) {
                       ArrayList<Element> asd = new ArrayList();
                        if (!vs.hasChildNodes()) {
                            nPadre.appendChild(vs);
                        } else {
                            NodeList temp = vs.getChildNodes();
                            if (temp.getLength() > 0) {
                                Node parent = temp.item((temp.getLength() - 1)).getParentNode();
                                asd.add((Element) parent);
                            }
                            for (int i = 0; i < temp.getLength(); i++) {
                                asd.add((Element) temp.item(i));
                            }
                            for (int i = 0; i < asd.size(); i++) {
                                nPadre.appendChild(asd.get(i));
                            }
                        }
                    }
                    if( t != null ) {
                        Element nType = xmlDocument.createElement("Type");
                        nType.setAttribute("Value",t);
                        nPadre.appendChild(nType);                        
                    }
                    RESULT = nPadre;
                :}
                ;

vardecls        ::=  /* Empty */
                |   vardecl:v PuntoComa vardecls:vs
                {:
                    iniXML();
                    if(v != null && vs == null ){
                        RESULT = v;
                    } else if(v == null && vs != null){
                        RESULT = vs;
                    } else if(v != null && vs != null){
                        vs.appendChild(v);
                        RESULT = vs;
                    } else RESULT = null;
                :} 
                |   error PuntoComa vardecls:vs 
                |   error vardecls:vs  
                ;

vardecl         ::= vars:vs DosPuntos type:t
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("VarDeclaration");
                    if (vs != null) { 
                        ArrayList<Element> asd = new ArrayList();
                        if (!vs.hasChildNodes()) {
                            nPadre.appendChild(vs);
                        } else {
                            NodeList temp = vs.getChildNodes();
                            if (temp.getLength() > 0) {
                                Node parent = temp.item((temp.getLength() - 1)).getParentNode();
                                asd.add((Element) parent);
                            }
                            for (int i = 0; i < temp.getLength(); i++) {
                                asd.add((Element) temp.item(i));
                            }
                            for (int i = 0; i < asd.size(); i++) {
                                nPadre.appendChild(asd.get(i));
                            }
                        }
                    }
                    nPadre.appendChild(t);
                    RESULT = nPadre;                    
                :}
                ;

vars            ::= var:v
                {:
                    iniXML();
                    RESULT = v;                    
                :}
                |  vars:vs Coma var:v
                {:
                    iniXML();
                    vs.appendChild(v);
                    RESULT = vs;                    
                :}
                ;

var             ::= Identificador:i
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ID");
                    nPadre.setAttribute("Value",i);            
                    RESULT = nPadre;                    
                :}
                ;

type            ::= identtype:it
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Type");
                    if(it != null) {
                        nPadre.setAttribute("Value",it);
                        RESULT = nPadre;
                    } else RESULT = null;
                :}
                |   arraytype:ats
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Type");
                    if(ats != null) {
                        nPadre.appendChild(ats);
                        RESULT = nPadre;
                    } else RESULT = null;
                :}
                ;

identtype       ::= TipoChar:c
                {:
                   RESULT = c;
                :}
                |   TipoString:c
                {:
                   RESULT = c;
                :}
                |   TipoBoolean:c
                {:
                   RESULT = c;
                :}
                |   TipoInteger:c
                {:
                   RESULT = c;
                :}
                ;


arraytype       ::= Array BracketAbrir literal:l1 PuntoPunto literal:l2 BracketCerrar Of arrayidenttype:t
                {:  
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArrayType");
                    if(l1 != null){nPadre.appendChild(l1);}
                    if(l2 != null){nPadre.appendChild(l2);}
                    if(t != null){nPadre.setAttribute("Type",t);}
                    RESULT = nPadre;
                :}
                ;

arrayidenttype  ::= TipoChar:c
                {:
                   RESULT = c;
                :}
                |   TipoBoolean:c
                {:
                   RESULT = c;
                :}
                |   TipoInteger:c
                {:
                   RESULT = c;
                :}
                ;

stmts           ::= stmt:s
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Statements");
                    if (s != null) { nPadre.appendChild(s); RESULT = nPadre;}
                    
                :}
                |   stmt:s PuntoComa stmts:ss
                {:
                    Element nPadre = xmlDocument.createElement("Statements");
                    iniXML();
                    if(s != null && ss == null){
                        RESULT = s;
                    } else if(s == null && ss != null){
                        RESULT = ss;
                    } else if(s != null && ss != null){
                        nPadre.appendChild(s);
                        nPadre.appendChild(ss);
                        RESULT = nPadre;
                    } else RESULT = null;
                :}
                |   error stmts:s 
                ;

stmt            ::= /* Empty */ {: RESULT = null; :}
                | assignstmt:s
                {:
                    iniXML();               
                    RESULT = s;
                :}
                | ifstmt:s
                {:
                    iniXML();              
                    RESULT = s;
                :}
                | forstmt:s
                {:
                    iniXML();             
                    RESULT = s;
                :}
                | whilestmt:s
                {:
                    iniXML();   
                    RESULT = s;
                :}
                | repeatstmt:s
                {:
                    iniXML();          
                    RESULT = s;
                :}
                | readstmt:s
                {:
                    iniXML();          
                    RESULT = s;
                :}
                | writestmt:s
                {:
                    iniXML();       
                    RESULT = s;
                :}
                | blockstmt:s
                {:
                    iniXML();             
                    RESULT = s;
                :}
                |   stmt:s error  
                ;

blockstmt       ::= Begin stmts:s End
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Body");
                    if (s != null) { nPadre.appendChild(s); }             
                    RESULT = nPadre;
                :}
                |   blockstmt error
                ;

assignstmt      ::= var:i DosPuntosIgual expr:e 
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Assignment");
                    if (i != null) { nPadre.appendChild(i); }
                    if (e != null) { nPadre.appendChild(e); }                   
                    RESULT = nPadre;
                :}  
                |   assignstmt error
                ;

ifstmt          ::= If expr:e Then stmt:s Else stmt:s2
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("IfStatement");
                    if (e != null) { nPadre.appendChild(e); }         
                    if (s != null) { nPadre.appendChild(s); }
                    if (s2 != null) { nPadre.appendChild(s2); }
                    RESULT = nPadre;
                :}
                |   If expr:e Then stmt:s
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("IfStatement");
                    if (e != null) { nPadre.appendChild(e); }         
                    if (s != null) { nPadre.appendChild(s); }
                    RESULT = nPadre;
                :}
                |   ifstmt error
                |   error Else stmt:s2
                ;

forstmt         ::= For assignstmt:a To expr:e Do stmts:s
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ForStatement");
                    if (a != null) { nPadre.appendChild(a); }
                    if (e != null) { nPadre.appendChild(e); }
                    if (s != null) { nPadre.appendChild(s); }
                    RESULT = nPadre;
                :}
                |   forstmt error
                ;

whilestmt       ::= While expr:e Do stmt:s
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("WhileStatement");
                    if (e != null) { nPadre.appendChild(e); }
                    if (s != null) { nPadre.appendChild(s); }
                    RESULT = nPadre;
                :}
                |   whilestmt error
                ;

repeatstmt      ::= Repeat stmts:s Until expr:e
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RepeatStatement");
                    if (s != null) { nPadre.appendChild(s); }
                    if (e != null) { nPadre.appendChild(e); }
                    RESULT = nPadre;
                :}
                |   repeatstmt error
                ;

writestmt       ::= Write ParentesisAbrir string:s ParentesisCerrar
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("WriteStatement");
                    if (s != null) { nPadre.appendChild(s); }
                    RESULT = nPadre;
                :}
                |   Write ParentesisAbrir string:s Coma var:v ParentesisCerrar
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("WriteStatement");
                    if (s != null) { nPadre.appendChild(s); }
                    if (v != null) { nPadre.appendChild(v); }
                    RESULT = nPadre;
                :}
                |   error ParentesisCerrar
                ;

readstmt        ::= Read ParentesisAbrir var:v ParentesisCerrar
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ReadStatement");
                    if (v != null) { nPadre.appendChild(v); }
                    RESULT = nPadre;
                :}
                |   readstmt error
                ;

expr            ::= literal:l 
                {:
                    iniXML();                
                    RESULT = l;
                :}
                |   var:v
                {:
                    iniXML();             
                    RESULT = v;
                :}
                |   var:v ParentesisAbrir exprlist:el ParentesisCerrar
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("FunctionCall");
                    if (v != null) { nPadre.appendChild(v);}
                    if (el != null) { nPadre.appendChild(el);}
                    RESULT = nPadre;
                :}
                |   var:v ParentesisAbrir ParentesisCerrar
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("FunctionCall");
                    if (v != null) { nPadre.appendChild(v);}
                :}
                |   expr:e1 opRelacion:op expr:e2
                {:
                    iniXML();
                    op.appendChild(e1);
                    op.appendChild(e2);
                    RESULT = op;
                :}
                |   expr:e1 opArit:op expr:e2
                {:
                    iniXML();
                    op.appendChild(e1);
                    op.appendChild(e2);
                    RESULT = op;
                :}
                |   opUnario:op expr:e
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Expression");
                    if (op != null) { nPadre.appendChild(op);}
                    if (e != null) { nPadre.appendChild(e);}
                    RESULT = nPadre;
                :}
                |   exprLogical:e
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Expression");
                    if (e != null) { nPadre.appendChild(e);}
                    RESULT = nPadre;
                :}
                ;

exprLogical     ::= ParentesisAbrir expr:e1 ParentesisCerrar exprOpLog:e2
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Expression");
                    if (e1 != null) { nPadre.appendChild(e1);}
                    if (e2 != null) { nPadre.appendChild(e2);}
                    RESULT = nPadre;
                :}
                ;

exprOpLog       ::= /* Empty */
                |   opLogico:op exprLogical:e
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Expression");
                    if (op != null) { nPadre.appendChild(op);}
                    if (e != null)  { nPadre.appendChild(e);}
                    RESULT = nPadre;
                :}
                ;

opRelacion      ::= OperadorIgual:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RelationalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorDiferente:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RelationalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorMayor:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RelationalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorMenor:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RelationalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorMenorIgual:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RelationalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorMayorIgual:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("RelationalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                ;


opArit          ::= OperadorSuma:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArithmeticOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorResta:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArithmeticOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorMultiplicacion:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArithmeticOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorDivision:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArithmeticOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorMod:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArithmeticOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorDivisionSpecial:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ArithmeticOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                ;

opUnario        ::= OperadorNot:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("UnaryOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorSuma:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("UnaryOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorResta:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("UnaryOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :} 
                ;

opLogico        ::= OperadorAnd:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("LogicalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                |   OperadorOr:op
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("LogicalOp");
                    if (op != null) { nPadre.setAttribute("Value",op);}
                    RESULT = nPadre;
                :}
                ;

exprlist        ::= expr:e
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ExprList");
                    if (e != null) { nPadre.appendChild(e);}
                    RESULT = nPadre;
                :}
                |   expr:e Coma exprlist:el
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("ExprList");
                    if (e != null) { nPadre.appendChild(e);}
                    if (el != null) { nPadre.appendChild(el);}
                    RESULT = nPadre;
                :}
                ;

literal         ::= integer:i
                {:
                    iniXML();
                    RESULT = i;
                :}
                |   character:c
                {:
                    iniXML();
                    RESULT = c;
                :}                
                |   boolean:b
                {:
                    iniXML();
                    RESULT = b;
                :}
                |   string:s
                {:
                    iniXML();
                    RESULT = s;
                :}
                ;

integer         ::= LiteralEntero:i 
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Integer");
                    nPadre.setAttribute("Value",i.toString());
                    RESULT = nPadre;
                :}
                ;

character       ::= LiteralCaracter:c
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Character");
                    nPadre.setAttribute("Value",c.toString());            
                    RESULT = nPadre;
                :}
                ;

boolean         ::= LiteralBoolean:b
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("Boolean");
                    nPadre.setAttribute("Value",b);          
                    RESULT = nPadre;
                :}
                ;

string          ::= LiteralString:s
                {:
                    iniXML();
                    Element nPadre = xmlDocument.createElement("String");
                    nPadre.setAttribute("Value",s);
                    RESULT = nPadre;
                :}
                ;